spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
